/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell Core i7
 */
public class InicioSesionForm extends javax.swing.JFrame {


    public InicioSesionForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        

        //this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBackground = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pfContrasena = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblIniciarSesion1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jpnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        jpnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblIniciarSesion.setText("INICIAR SESIÓN");
        jpnlBackground.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUsuario.setText("USUARIO");
        jpnlBackground.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jpnlBackground.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 410, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jpnlBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 410, 20));

        lblContrasena.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblContrasena.setText("CONTRASEÑA");
        jpnlBackground.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jpnlBackground.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 410, 20));

        pfContrasena.setForeground(new java.awt.Color(204, 204, 204));
        pfContrasena.setText("jPasswordField1");
        pfContrasena.setBorder(null);
        pfContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfContrasenaActionPerformed(evt);
            }
        });
        jpnlBackground.add(pfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 410, 30));

        btnEntrar.setBackground(new java.awt.Color(51, 102, 255));
        btnEntrar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jpnlBackground.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 360, 100, 40));

        lblIniciarSesion1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(0, 0, 102));
        lblIniciarSesion1.setText("SISTEMA MAK");
        jpnlBackground.add(lblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if (txtUsuario.getText().equals("Ingrese su nombre de usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(pfContrasena.getPassword()).isEmpty()) {
            pfContrasena.setText("********");
            pfContrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pfContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfContrasenaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        
        MenuAdministradorVista menuAdmin = new MenuAdministradorVista();
        menuAdmin.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpnlBackground;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
