/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Dell Core i7
 */
public class MenuAdministradorVista extends javax.swing.JFrame {


    public MenuAdministradorVista() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jpnlBackground = new javax.swing.JPanel();
        lblGestionarUsuarios = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarUsuarios = new javax.swing.JButton();
        btnListarUsuarios = new javax.swing.JButton();
        btnActualizarUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarUsuarios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        jpnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestionarUsuarios.setFont(new java.awt.Font("Roboto Black", 1, 30)); // NOI18N
        lblGestionarUsuarios.setText("GESTIONAR USUARIOS");
        jpnlBackground.add(lblGestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 340, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnRegistrarUsuarios.setBackground(new java.awt.Color(51, 102, 255));
        btnRegistrarUsuarios.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnRegistrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUsuarios.setText("REGISTRAR USUARIOS");
        btnRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariosActionPerformed(evt);
            }
        });

        btnListarUsuarios.setBackground(new java.awt.Color(255, 255, 204));
        btnListarUsuarios.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnListarUsuarios.setForeground(new java.awt.Color(0, 0, 102));
        btnListarUsuarios.setText("LISTAR USUARIOS");
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });

        btnActualizarUsuarios.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizarUsuarios.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnActualizarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarUsuarios.setText("ACTUALIZAR USUARIOS");
        btnActualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Black", 1, 18)); // NOI18N

        btnEliminarUsuarios.setBackground(new java.awt.Color(255, 255, 204));
        btnEliminarUsuarios.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnEliminarUsuarios.setForeground(new java.awt.Color(0, 0, 102));
        btnEliminarUsuarios.setText("ELIMINAR USUARIOS");
        btnEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnActualizarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(btnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpnlBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 290, 240));

        btnRegresar.setBackground(new java.awt.Color(0, 204, 255));
        btnRegresar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jpnlBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 208, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        // TODO add your handling code here:
        
        MeListarUsuarioForm menuList = new MeListarUsuarioForm();
        menuList.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void btnActualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuariosActionPerformed
        // TODO add your handling code here:
        
        MeActualizarUsuarioForm menuAct = new MeActualizarUsuarioForm();
        menuAct.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnActualizarUsuariosActionPerformed

    private void btnEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuariosActionPerformed
        // TODO add your handling code here:
        
        MeEliminarUsuarioForm menuElim = new MeEliminarUsuarioForm();
        menuElim.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnEliminarUsuariosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        InicioSesionForm menuInicio = new InicioSesionForm();
        menuInicio.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariosActionPerformed
        // TODO add your handling code here:
        
        MeRegistrarUsuarioForm menuRegis = new MeRegistrarUsuarioForm();
        menuRegis.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnRegistrarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministradorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuarios;
    private javax.swing.JButton btnEliminarUsuarios;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JButton btnRegistrarUsuarios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel jpnlBackground;
    private javax.swing.JLabel lblGestionarUsuarios;
    // End of variables declaration//GEN-END:variables
}
